---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: Azure NetApp Files を使用すると、パフォーマンスを重視し、レイテンシの影響を受けやすいコアアプリケーションを Azure に移行して実行できます。クラウドにリファクタリングする必要はありません。 
---
= Azure NetApp Files の詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files を使用すると、パフォーマンスを重視し、レイテンシの影響を受けやすいコアアプリケーションを Azure に移行して実行できます。クラウドにリファクタリングする必要はありません。



== の機能

* 複数のプロトコルをサポートしているため、 Linux と Windows 両方のアプリケーションを Azure でシームレスに移行してスムーズに実行できます。
* 複数のパフォーマンス階層を使用することで、ワークロードのパフォーマンス要件に緊密に合わせることができます。
* SAP HANA 、 GDPR 、 HIPAA を含む業界をリードする認定資格を取得することで、最も要件の厳しいワークロードを Azure に移行できます。




== BlueXPのその他の機能

* NFSやSMBのデータをBlueXPからAzure NetApp Files に直接移行データ移行にはBlueXPのコピーと同期が活用されます。
+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["BlueXPのコピーと同期の詳細については、こちらをご覧ください"^]

* 人工知能（AI）ベースのテクノロジを使用するBlueXPの分類は、データのコンテキストを理解し、Azure NetApp Files アカウントに存在する機密データを特定するのに役立ちます。
+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXPの分類の詳細については、こちらをご覧ください"^]





== コスト

https://azure.microsoft.com/pricing/details/netapp/["Azure NetApp Files の価格設定を確認する"^]

サブスクリプションと充電は、BlueXPではなくAzure NetApp Files サービスによって管理されていることに注意してください。



== サポートされている地域

https://bluexp.netapp.com/cloud-volumes-global-regions["サポートされる Azure リージョンを表示します"^]



== サポートを受ける

Azure NetApp Files に関連したテクニカルサポートの問題については、 Azure ポータルを使用して Microsoft にサポートリクエストを記録してください。関連する Microsoft サブスクリプションを選択し、「 * ストレージ * 」の下の「 * Azure NetApp Files * 」サービス名を選択します。Microsoft サポートリクエストの作成に必要な残りの情報を入力します。



== 関連リンク

* link:https://bluexp.netapp.com/azure-netapp-files["ネットアップのBlueXP Webサイト：Azure NetApp Files"^]
* link:https://learn.microsoft.com/azure/azure-netapp-files/["Azure NetApp Files のドキュメント"^]
* link:https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["BlueXPのコピーと同期に関するドキュメント"^]

